/**
 * Full holiday catalog: every major celebration the app tracks.
 * Each entry contains date-rule, market scope, theme variant, and priority.
 */

import type { HolidayDefinition } from './types';

export const HOLIDAY_CATALOG: HolidayDefinition[] = [
  // ── January ──────────────────────────────────────────────────────
  {
    id: 'new_years_day',
    nameKey: 'holidays.newYearsDay',
    emoji: '🎆',
    markets: 'worldwide',
    rule: { kind: 'fixed', month: 1, day: 1 },
    windowHours: 48,
    priority: 100,
    theme: 'new_year',
    publicHoliday: true,
  },
  {
    id: 'blue_monday',
    nameKey: 'holidays.blueMonday',
    emoji: '😢',
    markets: ['GB', 'DE', 'FR', 'IT', 'ES', 'NL', 'BE', 'PL', 'SE', 'AT'],
    rule: { kind: 'nth_weekday', month: 1, week: 3, dayOfWeek: 1 },
    windowHours: 24,
    priority: 20,
    theme: 'winter',
  },
  {
    id: 'australia_day',
    nameKey: 'holidays.australiaDay',
    emoji: '🇦🇺',
    markets: ['AU'],
    rule: { kind: 'fixed', month: 1, day: 26 },
    windowHours: 24,
    priority: 60,
    theme: 'independence',
    publicHoliday: true,
  },
  {
    id: 'republic_day_india',
    nameKey: 'holidays.republicDayIndia',
    emoji: '🇮🇳',
    markets: ['IN'],
    rule: { kind: 'fixed', month: 1, day: 26 },
    windowHours: 24,
    priority: 60,
    theme: 'independence',
    publicHoliday: true,
  },
  {
    id: 'burns_night',
    nameKey: 'holidays.burnsNight',
    emoji: '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    markets: ['GB'],
    rule: { kind: 'fixed', month: 1, day: 25 },
    windowHours: 24,
    priority: 25,
    theme: 'cultural',
  },

  // ── February ─────────────────────────────────────────────────────
  {
    id: 'lunar_new_year',
    nameKey: 'holidays.lunarNewYear',
    emoji: '🐉',
    markets: ['CN', 'HK', 'TW', 'KR', 'VN', 'SG', 'MY', 'TH', 'MO', 'MN', 'ID'],
    rule: { kind: 'provider', providerId: 'lunar_new_year' },
    windowHours: 48,
    priority: 95,
    theme: 'lunar_new_year',
    publicHoliday: true,
  },
  {
    id: 'valentines_day',
    nameKey: 'holidays.valentinesDay',
    emoji: '❤️',
    markets: 'worldwide',
    rule: { kind: 'fixed', month: 2, day: 14 },
    windowHours: 24,
    priority: 70,
    theme: 'valentine',
  },
  {
    id: 'carnival',
    nameKey: 'holidays.carnival',
    emoji: '🎭',
    markets: ['BR', 'IT', 'US', 'JM', 'TT', 'CO', 'VE'],
    rule: { kind: 'provider', providerId: 'mardi_gras' },
    windowHours: 120,
    priority: 65,
    theme: 'carnival',
    publicHoliday: true,
  },
  {
    id: 'waitangi_day',
    nameKey: 'holidays.waitangiDay',
    emoji: '🇳🇿',
    markets: ['NZ'],
    rule: { kind: 'fixed', month: 2, day: 6 },
    windowHours: 24,
    priority: 55,
    theme: 'independence',
    publicHoliday: true,
  },
  {
    id: 'day_after_new_years_day',
    nameKey: 'holidays.dayAfterNewYearsDay',
    emoji: '🎇',
    markets: ['NZ'],
    rule: { kind: 'fixed', month: 1, day: 2 },
    windowHours: 24,
    priority: 52,
    theme: 'new_year',
    publicHoliday: true,
  },
  {
    id: 'family_day_ca',
    nameKey: 'holidays.familyDay',
    emoji: '👨‍👩‍👧‍👦',
    markets: ['CA'],
    rule: { kind: 'nth_weekday', month: 2, week: 3, dayOfWeek: 1 },
    windowHours: 24,
    priority: 30,
    theme: 'cultural',
    publicHoliday: true,
  },

  // ── March ────────────────────────────────────────────────────────
  {
    id: 'holi',
    nameKey: 'holidays.holi',
    emoji: '🎨',
    markets: ['IN', 'NP'],
    rule: { kind: 'provider', providerId: 'holi' },
    windowHours: 48,
    priority: 75,
    theme: 'spring',
    publicHoliday: true,
  },
  {
    id: 'intl_womens_day',
    nameKey: 'holidays.intlWomensDay',
    emoji: '♀️',
    markets: 'worldwide',
    rule: { kind: 'fixed', month: 3, day: 8 },
    windowHours: 24,
    priority: 40,
    theme: 'spring',
  },
  {
    id: 'white_day',
    nameKey: 'holidays.whiteDay',
    emoji: '🤍',
    markets: ['JP', 'KR', 'CN', 'TW', 'VN'],
    rule: { kind: 'fixed', month: 3, day: 14 },
    windowHours: 24,
    priority: 40,
    theme: 'valentine',
  },
  {
    id: 'st_patricks_day',
    nameKey: 'holidays.stPatricksDay',
    emoji: '☘️',
    markets: ['IE', 'GB', 'US', 'CA', 'AU'],
    rule: { kind: 'fixed', month: 3, day: 17 },
    windowHours: 24,
    priority: 55,
    theme: 'spring',
    publicHoliday: true,
  },
  {
    id: 'nowruz',
    nameKey: 'holidays.nowruz',
    emoji: '🌿',
    markets: ['IR', 'AF', 'AZ', 'KZ', 'KG', 'TJ', 'TM', 'UZ'],
    rule: { kind: 'provider', providerId: 'nowruz' },
    windowHours: 48,
    priority: 90,
    theme: 'spring',
    publicHoliday: true,
  },
  {
    id: 'eid_al_fitr',
    nameKey: 'holidays.eidAlFitr',
    emoji: '🌙',
    markets: ['SA', 'AE', 'OM', 'QA', 'BH', 'KW', 'YE', 'EG', 'TR', 'MY', 'ID', 'PK', 'BD', 'MA', 'DZ', 'TN', 'IQ', 'JO', 'SY', 'LB'],
    rule: { kind: 'provider', providerId: 'eid_al_fitr' },
    windowHours: 72,
    priority: 85,
    theme: 'ramadan',
    publicHoliday: true,
  },
  {
    id: 'first_day_spring',
    nameKey: 'holidays.firstDayOfSpring',
    emoji: '🌸',
    markets: 'worldwide',
    rule: { kind: 'fixed', month: 3, day: 20 },
    windowHours: 24,
    priority: 20,
    theme: 'spring',
  },

  // ── April ────────────────────────────────────────────────────────
  {
    id: 'april_fools',
    nameKey: 'holidays.aprilFools',
    emoji: '🤡',
    markets: 'worldwide',
    rule: { kind: 'fixed', month: 4, day: 1 },
    windowHours: 24,
    priority: 30,
    theme: 'spring',
  },
  {
    id: 'easter',
    nameKey: 'holidays.easter',
    emoji: '🐣',
    markets: 'worldwide',
    rule: { kind: 'provider', providerId: 'easter' },
    windowHours: 48,
    priority: 80,
    theme: 'easter',
    publicHoliday: true,
  },
  {
    id: 'good_friday',
    nameKey: 'holidays.goodFriday',
    emoji: '✝️',
    markets: 'worldwide',
    rule: { kind: 'provider', providerId: 'good_friday' },
    windowHours: 24,
    priority: 50,
    theme: 'easter',
    publicHoliday: true,
  },
  {
    id: 'songkran',
    nameKey: 'holidays.songkran',
    emoji: '💦',
    markets: ['TH', 'LA', 'KH', 'MM'],
    rule: { kind: 'fixed', month: 4, day: 13 },
    windowHours: 72,
    priority: 80,
    theme: 'cultural',
    publicHoliday: true,
  },
  {
    id: 'earth_day',
    nameKey: 'holidays.earthDay',
    emoji: '🌍',
    markets: 'worldwide',
    rule: { kind: 'fixed', month: 4, day: 22 },
    windowHours: 24,
    priority: 30,
    theme: 'spring',
  },
  {
    id: 'tiradentes',
    nameKey: 'holidays.tiradentes',
    emoji: '🇧🇷',
    markets: ['BR'],
    rule: { kind: 'fixed', month: 4, day: 21 },
    windowHours: 24,
    priority: 58,
    theme: 'independence',
    publicHoliday: true,
  },
  {
    id: 'anzac_day',
    nameKey: 'holidays.anzacDay',
    emoji: '🎖️',
    markets: ['AU', 'NZ'],
    rule: { kind: 'fixed', month: 4, day: 25 },
    windowHours: 24,
    priority: 55,
    theme: 'cultural',
    publicHoliday: true,
  },
  {
    id: 'kings_day',
    nameKey: 'holidays.kingsDay',
    emoji: '🧡',
    markets: ['NL'],
    rule: { kind: 'fixed', month: 4, day: 27 },
    windowHours: 24,
    priority: 60,
    theme: 'independence',
    publicHoliday: true,
  },
  {
    id: 'passover',
    nameKey: 'holidays.passover',
    emoji: '✡️',
    markets: ['IL'],
    rule: { kind: 'provider', providerId: 'passover' },
    windowHours: 48,
    priority: 70,
    theme: 'cultural',
    publicHoliday: true,
  },
  {
    id: 'golden_week_jp',
    nameKey: 'holidays.goldenWeek',
    emoji: '🇯🇵',
    markets: ['JP'],
    rule: { kind: 'fixed', month: 4, day: 29 },
    windowHours: 168,
    priority: 60,
    theme: 'spring',
    publicHoliday: true,
  },

  // ── May ──────────────────────────────────────────────────────────
  {
    id: 'workers_day',
    nameKey: 'holidays.workersDay',
    emoji: '⚒️',
    markets: 'worldwide',
    rule: { kind: 'fixed', month: 5, day: 1 },
    windowHours: 24,
    priority: 35,
    theme: 'spring',
    publicHoliday: true,
  },
  {
    id: 'vesak',
    nameKey: 'holidays.vesak',
    emoji: '☸️',
    markets: ['TH', 'LK', 'MM', 'KH', 'LA', 'SG', 'ID', 'MY', 'VN', 'IN', 'NP'],
    rule: { kind: 'provider', providerId: 'vesak' },
    windowHours: 24,
    priority: 50,
    theme: 'cultural',
    publicHoliday: true,
  },
  {
    id: 'cinco_de_mayo',
    nameKey: 'holidays.cincoDeMayo',
    emoji: '🇲🇽',
    markets: ['MX', 'US'],
    rule: { kind: 'fixed', month: 5, day: 5 },
    windowHours: 24,
    priority: 50,
    theme: 'cultural',
  },
  {
    id: 'europe_day',
    nameKey: 'holidays.europeDay',
    emoji: '🇪🇺',
    markets: ['DE', 'FR', 'IT', 'ES', 'NL', 'BE', 'AT', 'PL', 'SE', 'PT', 'IE', 'FI', 'DK', 'GR', 'CZ', 'HU', 'RO', 'BG', 'HR', 'SK', 'SI', 'LT', 'LV', 'EE', 'LU', 'MT', 'CY'],
    rule: { kind: 'fixed', month: 5, day: 9 },
    windowHours: 24,
    priority: 25,
    theme: 'cultural',
  },
  {
    id: 'mothers_day',
    nameKey: 'holidays.mothersDay',
    emoji: '💐',
    markets: ['US', 'CA', 'AU', 'NZ', 'DE', 'IT', 'JP', 'BE', 'BR', 'CL', 'CO', 'CU', 'CZ', 'DK', 'EC', 'FI', 'GR', 'HU', 'IN', 'NL', 'PE', 'SK', 'TW', 'TR', 'UY', 'VE'],
    rule: { kind: 'nth_weekday', month: 5, week: 2, dayOfWeek: 0 },
    windowHours: 24,
    priority: 60,
    theme: 'spring',
  },
  {
    id: 'victoria_day',
    nameKey: 'holidays.victoriaDay',
    emoji: '👑',
    markets: ['CA'],
    rule: { kind: 'last_weekday', month: 5, dayOfWeek: 1 },
    windowHours: 24,
    priority: 35,
    theme: 'cultural',
    publicHoliday: true,
  },
  {
    id: 'memorial_day',
    nameKey: 'holidays.memorialDay',
    emoji: '🇺🇸',
    markets: ['US'],
    rule: { kind: 'last_weekday', month: 5, dayOfWeek: 1 },
    windowHours: 24,
    priority: 50,
    theme: 'independence',
    publicHoliday: true,
  },

  // ── June ─────────────────────────────────────────────────────────
  {
    id: 'pride_month',
    nameKey: 'holidays.prideMonth',
    emoji: '🏳️‍🌈',
    markets: 'worldwide',
    rule: { kind: 'fixed', month: 6, day: 1 },
    windowHours: 24,
    priority: 35,
    theme: 'pride',
  },
  {
    id: 'dragon_boat',
    nameKey: 'holidays.dragonBoat',
    emoji: '🐲',
    markets: ['CN', 'HK', 'TW', 'MO'],
    rule: { kind: 'provider', providerId: 'dragon_boat' },
    windowHours: 24,
    priority: 55,
    theme: 'cultural',
    publicHoliday: true,
  },
  {
    id: 'fathers_day',
    nameKey: 'holidays.fathersDay',
    emoji: '👔',
    markets: ['US', 'CA', 'GB', 'FR', 'JP', 'IN', 'AR', 'ZA', 'MX', 'CO', 'VE', 'PE'],
    rule: { kind: 'nth_weekday', month: 6, week: 3, dayOfWeek: 0 },
    windowHours: 24,
    priority: 55,
    theme: 'summer',
  },
  {
    id: 'dia_dos_namorados',
    nameKey: 'holidays.diaDosNamorados',
    emoji: '💘',
    markets: ['BR'],
    rule: { kind: 'fixed', month: 6, day: 12 },
    windowHours: 24,
    priority: 60,
    theme: 'valentine',
  },
  {
    id: 'corpus_christi_brazil',
    nameKey: 'holidays.corpusChristiBrazil',
    emoji: '⛪',
    markets: ['BR'],
    rule: { kind: 'provider', providerId: 'corpus_christi' },
    windowHours: 24,
    priority: 60,
    theme: 'cultural',
    publicHoliday: true,
  },
  {
    id: 'summer_solstice',
    nameKey: 'holidays.summerSolstice',
    emoji: '☀️',
    markets: 'worldwide',
    rule: { kind: 'fixed', month: 6, day: 21 },
    windowHours: 24,
    priority: 20,
    theme: 'summer',
  },
  {
    id: 'midsummer',
    nameKey: 'holidays.midsummer',
    emoji: '🌻',
    markets: ['SE', 'FI', 'NO', 'DK', 'IS', 'EE', 'LV', 'LT'],
    rule: { kind: 'fixed', month: 6, day: 24 },
    windowHours: 48,
    priority: 60,
    theme: 'summer',
    publicHoliday: true,
  },

  // ── July ─────────────────────────────────────────────────────────
  {
    id: 'canada_day',
    nameKey: 'holidays.canadaDay',
    emoji: '🇨🇦',
    markets: ['CA'],
    rule: { kind: 'fixed', month: 7, day: 1 },
    windowHours: 24,
    priority: 70,
    theme: 'independence',
    publicHoliday: true,
  },
  {
    id: 'independence_day_us',
    nameKey: 'holidays.independenceDayUS',
    emoji: '🇺🇸',
    markets: ['US'],
    rule: { kind: 'fixed', month: 7, day: 4 },
    windowHours: 24,
    priority: 80,
    theme: 'independence',
    publicHoliday: true,
  },
  {
    id: 'tanabata',
    nameKey: 'holidays.tanabata',
    emoji: '🎋',
    markets: ['JP'],
    rule: { kind: 'fixed', month: 7, day: 7 },
    windowHours: 24,
    priority: 40,
    theme: 'cultural',
  },
  {
    id: 'matariki',
    nameKey: 'holidays.matariki',
    emoji: '🌌',
    markets: ['NZ'],
    rule: { kind: 'provider', providerId: 'matariki' },
    windowHours: 24,
    priority: 70,
    theme: 'cultural',
    publicHoliday: true,
  },
  {
    id: 'bastille_day',
    nameKey: 'holidays.bastilleDay',
    emoji: '🇫🇷',
    markets: ['FR'],
    rule: { kind: 'fixed', month: 7, day: 14 },
    windowHours: 24,
    priority: 65,
    theme: 'independence',
    publicHoliday: true,
  },

  // ── August ───────────────────────────────────────────────────────
  {
    id: 'swiss_national_day',
    nameKey: 'holidays.swissNationalDay',
    emoji: '🇨🇭',
    markets: ['CH'],
    rule: { kind: 'fixed', month: 8, day: 1 },
    windowHours: 24,
    priority: 55,
    theme: 'independence',
    publicHoliday: true,
  },
  {
    id: 'civic_holiday_ca',
    nameKey: 'holidays.civicHoliday',
    emoji: '🍁',
    markets: ['CA'],
    rule: { kind: 'nth_weekday', month: 8, week: 1, dayOfWeek: 1 },
    windowHours: 24,
    priority: 25,
    theme: 'summer',
    publicHoliday: true,
  },
  {
    id: 'national_day_sg',
    nameKey: 'holidays.nationalDaySG',
    emoji: '🇸🇬',
    markets: ['SG'],
    rule: { kind: 'fixed', month: 8, day: 9 },
    windowHours: 24,
    priority: 60,
    theme: 'independence',
    publicHoliday: true,
  },
  {
    id: 'fathers_day_brazil',
    nameKey: 'holidays.fathersDayBrazil',
    emoji: '👨',
    markets: ['BR'],
    rule: { kind: 'nth_weekday', month: 8, week: 2, dayOfWeek: 0 },
    windowHours: 24,
    priority: 58,
    theme: 'summer',
  },
  {
    id: 'obon',
    nameKey: 'holidays.obon',
    emoji: '🏮',
    markets: ['JP'],
    rule: { kind: 'fixed', month: 8, day: 13 },
    windowHours: 72,
    priority: 50,
    theme: 'cultural',
  },
  {
    id: 'independence_day_india',
    nameKey: 'holidays.independenceDayIndia',
    emoji: '🇮🇳',
    markets: ['IN'],
    rule: { kind: 'fixed', month: 8, day: 15 },
    windowHours: 24,
    priority: 70,
    theme: 'independence',
    publicHoliday: true,
  },

  // ── September ────────────────────────────────────────────────────
  {
    id: 'labor_day_us',
    nameKey: 'holidays.laborDay',
    emoji: '💪',
    markets: ['US', 'CA'],
    rule: { kind: 'nth_weekday', month: 9, week: 1, dayOfWeek: 1 },
    windowHours: 24,
    priority: 45,
    theme: 'fall',
    publicHoliday: true,
  },
  {
    id: 'brazilian_independence',
    nameKey: 'holidays.brazilianIndependence',
    emoji: '🇧🇷',
    markets: ['BR'],
    rule: { kind: 'fixed', month: 9, day: 7 },
    windowHours: 24,
    priority: 60,
    theme: 'independence',
    publicHoliday: true,
  },
  {
    id: 'mexican_independence',
    nameKey: 'holidays.mexicanIndependence',
    emoji: '🇲🇽',
    markets: ['MX'],
    rule: { kind: 'fixed', month: 9, day: 16 },
    windowHours: 24,
    priority: 65,
    theme: 'independence',
    publicHoliday: true,
  },
  {
    id: 'chuseok',
    nameKey: 'holidays.chuseok',
    emoji: '🌕',
    markets: ['KR'],
    rule: { kind: 'provider', providerId: 'chuseok' },
    windowHours: 72,
    priority: 70,
    theme: 'fall',
    publicHoliday: true,
  },
  {
    id: 'oktoberfest',
    nameKey: 'holidays.oktoberfest',
    emoji: '🍺',
    markets: ['DE', 'AT', 'CH'],
    rule: { kind: 'provider', providerId: 'oktoberfest' },
    windowHours: 24,
    priority: 45,
    theme: 'fall',
  },
  {
    id: 'first_day_fall',
    nameKey: 'holidays.firstDayOfFall',
    emoji: '🍂',
    markets: 'worldwide',
    rule: { kind: 'fixed', month: 9, day: 22 },
    windowHours: 24,
    priority: 15,
    theme: 'fall',
  },
  {
    id: 'our_lady_aparecida',
    nameKey: 'holidays.ourLadyAparecida',
    emoji: '🙏',
    markets: ['BR'],
    rule: { kind: 'fixed', month: 10, day: 12 },
    windowHours: 24,
    priority: 62,
    theme: 'cultural',
    publicHoliday: true,
  },
  {
    id: 'teachers_day_brazil',
    nameKey: 'holidays.teachersDayBrazil',
    emoji: '🍎',
    markets: ['BR'],
    rule: { kind: 'fixed', month: 10, day: 15 },
    windowHours: 24,
    priority: 40,
    theme: 'cultural',
  },
  {
    id: 'public_service_day_brazil',
    nameKey: 'holidays.publicServiceDayBrazil',
    emoji: '🏛️',
    markets: ['BR'],
    rule: { kind: 'fixed', month: 10, day: 28 },
    windowHours: 24,
    priority: 35,
    theme: 'cultural',
    publicHoliday: true,
  },
  {
    id: 'kings_birthday_nz',
    nameKey: 'holidays.kingsBirthdayNZ',
    emoji: '👑',
    markets: ['NZ'],
    rule: { kind: 'nth_weekday', month: 6, week: 1, dayOfWeek: 1 },
    windowHours: 24,
    priority: 55,
    theme: 'cultural',
    publicHoliday: true,
  },
  {
    id: 'labour_day_nz',
    nameKey: 'holidays.labourDayNZ',
    emoji: '🛠️',
    markets: ['NZ'],
    rule: { kind: 'nth_weekday', month: 10, week: 4, dayOfWeek: 1 },
    windowHours: 24,
    priority: 55,
    theme: 'fall',
    publicHoliday: true,
  },
  {
    id: 'rosh_hashanah',
    nameKey: 'holidays.roshHashanah',
    emoji: '🍯',
    markets: ['IL'],
    rule: { kind: 'provider', providerId: 'rosh_hashanah' },
    windowHours: 48,
    priority: 75,
    theme: 'cultural',
    publicHoliday: true,
  },

  // ── October ──────────────────────────────────────────────────────
  {
    id: 'golden_week_cn',
    nameKey: 'holidays.goldenWeekCN',
    emoji: '🇨🇳',
    markets: ['CN'],
    rule: { kind: 'fixed', month: 10, day: 1 },
    windowHours: 168,
    priority: 60,
    theme: 'cultural',
    publicHoliday: true,
  },
  {
    id: 'mid_autumn',
    nameKey: 'holidays.midAutumn',
    emoji: '🥮',
    markets: ['CN', 'HK', 'TW', 'VN', 'KR', 'SG', 'MY'],
    rule: { kind: 'provider', providerId: 'mid_autumn' },
    windowHours: 24,
    priority: 60,
    theme: 'fall',
    publicHoliday: true,
  },
  {
    id: 'canadian_thanksgiving',
    nameKey: 'holidays.canadianThanksgiving',
    emoji: '🦃',
    markets: ['CA'],
    rule: { kind: 'nth_weekday', month: 10, week: 2, dayOfWeek: 1 },
    windowHours: 24,
    priority: 60,
    theme: 'thanksgiving',
    publicHoliday: true,
  },
  {
    id: 'diwali',
    nameKey: 'holidays.diwali',
    emoji: '🪔',
    markets: ['IN', 'NP', 'LK', 'MY', 'SG', 'FJ', 'TT', 'GY', 'MU'],
    rule: { kind: 'provider', providerId: 'diwali' },
    windowHours: 120,
    priority: 85,
    theme: 'diwali',
    publicHoliday: true,
  },
  {
    id: 'halloween',
    nameKey: 'holidays.halloween',
    emoji: '🎃',
    markets: ['US', 'CA', 'GB', 'IE', 'AU', 'NZ', 'DE', 'FR', 'IT', 'ES', 'NL', 'BE', 'AT', 'SE', 'NO', 'DK', 'JP'],
    rule: { kind: 'fixed', month: 10, day: 31 },
    windowHours: 24,
    priority: 70,
    theme: 'halloween',
  },

  // ── November ─────────────────────────────────────────────────────
  {
    id: 'dia_de_los_muertos',
    nameKey: 'holidays.diaDeLosMuertos',
    emoji: '💀',
    markets: ['MX', 'GT', 'HN', 'SV', 'CO', 'EC', 'PE', 'BO'],
    rule: { kind: 'fixed', month: 11, day: 1 },
    windowHours: 48,
    priority: 65,
    theme: 'halloween',
  },
  {
    id: 'remembrance_day',
    nameKey: 'holidays.remembranceDay',
    emoji: '🌺',
    markets: ['GB', 'CA', 'AU', 'NZ'],
    rule: { kind: 'fixed', month: 11, day: 11 },
    windowHours: 24,
    priority: 45,
    theme: 'fall',
    publicHoliday: true,
  },
  {
    id: 'singles_day',
    nameKey: 'holidays.singlesDay',
    emoji: '🛒',
    markets: ['CN'],
    rule: { kind: 'fixed', month: 11, day: 11 },
    windowHours: 24,
    priority: 50,
    theme: 'cultural',
  },
  {
    id: 'thanksgiving_us',
    nameKey: 'holidays.thanksgivingUS',
    emoji: '🦃',
    markets: ['US'],
    rule: { kind: 'nth_weekday', month: 11, week: 4, dayOfWeek: 4 },
    windowHours: 24,
    priority: 80,
    theme: 'thanksgiving',
    publicHoliday: true,
  },
  {
    id: 'black_friday',
    nameKey: 'holidays.blackFriday',
    emoji: '🏷️',
    markets: 'worldwide',
    rule: { kind: 'nth_weekday', month: 11, week: 4, dayOfWeek: 5 },
    windowHours: 24,
    priority: 45,
    theme: 'fall',
  },
  {
    id: 'all_souls_day_brazil',
    nameKey: 'holidays.allSoulsDayBrazil',
    emoji: '🕯️',
    markets: ['BR'],
    rule: { kind: 'fixed', month: 11, day: 2 },
    windowHours: 24,
    priority: 55,
    theme: 'cultural',
    publicHoliday: true,
  },
  {
    id: 'republic_proclamation_brazil',
    nameKey: 'holidays.republicProclamationBrazil',
    emoji: '🇧🇷',
    markets: ['BR'],
    rule: { kind: 'fixed', month: 11, day: 15 },
    windowHours: 24,
    priority: 58,
    theme: 'independence',
    publicHoliday: true,
  },
  {
    id: 'zumbi_day_brazil',
    nameKey: 'holidays.zumbiDayBrazil',
    emoji: '✊🏿',
    markets: ['BR'],
    rule: { kind: 'fixed', month: 11, day: 20 },
    windowHours: 24,
    priority: 52,
    theme: 'cultural',
    publicHoliday: true,
  },

  // ── December ─────────────────────────────────────────────────────
  {
    id: 'st_nicholas',
    nameKey: 'holidays.stNicholas',
    emoji: '🎅',
    markets: ['DE', 'NL', 'BE', 'AT', 'CH', 'LU'],
    rule: { kind: 'fixed', month: 12, day: 6 },
    windowHours: 24,
    priority: 40,
    theme: 'christmas',
  },
  {
    id: 'hanukkah',
    nameKey: 'holidays.hanukkah',
    emoji: '🕎',
    markets: ['IL', 'US', 'CA', 'GB', 'FR', 'AR'],
    rule: { kind: 'provider', providerId: 'hanukkah' },
    windowHours: 192,
    priority: 65,
    theme: 'cultural',
  },
  {
    id: 'first_day_winter',
    nameKey: 'holidays.firstDayOfWinter',
    emoji: '❄️',
    markets: 'worldwide',
    rule: { kind: 'fixed', month: 12, day: 21 },
    windowHours: 24,
    priority: 15,
    theme: 'winter',
  },
  {
    id: 'christmas',
    nameKey: 'holidays.christmas',
    emoji: '🎄',
    markets: 'worldwide',
    rule: { kind: 'fixed', month: 12, day: 25 },
    windowHours: 48,
    priority: 95,
    theme: 'christmas',
    publicHoliday: true,
  },
  {
    id: 'boxing_day',
    nameKey: 'holidays.boxingDay',
    emoji: '🎁',
    markets: ['GB', 'CA', 'AU', 'NZ', 'ZA', 'NG', 'KE', 'HK'],
    rule: { kind: 'fixed', month: 12, day: 26 },
    windowHours: 24,
    priority: 45,
    theme: 'christmas',
    publicHoliday: true,
  },
  {
    id: 'kwanzaa',
    nameKey: 'holidays.kwanzaa',
    emoji: '🕯️',
    markets: ['US'],
    rule: { kind: 'fixed', month: 12, day: 26 },
    windowHours: 168,
    priority: 40,
    theme: 'cultural',
  },
  {
    id: 'new_years_eve',
    nameKey: 'holidays.newYearsEve',
    emoji: '🥂',
    markets: 'worldwide',
    rule: { kind: 'fixed', month: 12, day: 31 },
    windowHours: 24,
    priority: 90,
    theme: 'new_year',
  },

  // ── Additional cultural / religious ──────────────────────────────
  {
    id: 'ethiopian_new_year',
    nameKey: 'holidays.ethiopianNewYear',
    emoji: '🇪🇹',
    markets: ['ET'],
    rule: { kind: 'provider', providerId: 'ethiopian_new_year' },
    windowHours: 48,
    priority: 90,
    theme: 'cultural',
    publicHoliday: true,
  },
  {
    id: 'islamic_new_year',
    nameKey: 'holidays.islamicNewYear',
    emoji: '☪️',
    markets: ['SA', 'AE', 'OM', 'QA', 'BH', 'KW', 'YE', 'EG', 'TR', 'MY', 'ID', 'PK'],
    rule: { kind: 'provider', providerId: 'islamic_new_year' },
    windowHours: 24,
    priority: 70,
    theme: 'ramadan',
    publicHoliday: true,
  },
  {
    id: 'ramadan',
    nameKey: 'holidays.ramadan',
    emoji: '🌙',
    markets: ['SA', 'AE', 'OM', 'QA', 'BH', 'KW', 'YE', 'EG', 'TR', 'MY', 'ID', 'PK', 'BD', 'MA', 'DZ', 'TN', 'IQ', 'JO', 'SY', 'LB'],
    rule: { kind: 'provider', providerId: 'ramadan_start' },
    windowHours: 24,
    priority: 75,
    theme: 'ramadan',
    publicHoliday: true,
  },
  {
    id: 'bengali_new_year',
    nameKey: 'holidays.bengaliNewYear',
    emoji: '🌺',
    markets: ['BD', 'IN'],
    rule: { kind: 'fixed', month: 4, day: 14 },
    windowHours: 24,
    priority: 65,
    theme: 'cultural',
    publicHoliday: true,
  },
];
